### ISSUE TITLE
Map goes gray when resizing

### ISSUE THREAD

**Issue by Pikkuninja** [APT-project/city_info#19]
The map doesn't really appreciate being dynamically resized without anyone notifying it. Add a function to force redrawing / resizing of the map and find a good place to call it.

**Comment by antti-TIEA4** [comment]
When does this occur? When you resize browser? Or change device from the control panel? Or an UI element changes it?

**Comment by Pikkuninja** [comment]
Most often when the app is in tilemode or in another tab, then resize by changing emulated device or some other means, go back to map view and move the map.

**Comment by Pikkuninja** [comment]
Actually tilemode doesn't seem to trigger it. But anyways currently one way to fix the gray map is to go to tilemode and return to app.

**Comment by Pikkuninja** [comment]
#21
